//
//  TRRecipeDictonary.m
//  TangibleRecipe
//


#import "TRRecipeDictonary.h"
#import "TRFood.h"

@implementation TRRecipeDictonary
NSDictionary *recipesDictionary;

-(void)initDictonary{

    //AutoGenerated using process.rb-----
    recipesDictionary = @{@"ご飯+たまご" : @[[[TRFood alloc] initWithName:@"天津飯・天津丼" andId:@"13-119-882"], [[TRFood alloc] initWithName:@"オムライス" andId:@"14-121-553"], [[TRFood alloc] initWithName:@"ロコモコ" andId:@"14-125-569"], [[TRFood alloc] initWithName:@"カツ丼" andId:@"14-130-542"], [[TRFood alloc] initWithName:@"あんかけチャーハン" andId:@"14-131-892"], [[TRFood alloc] initWithName:@"アレンジチャーハン" andId:@"14-131-893"], [[TRFood alloc] initWithName:@"クッパ" andId:@"14-133-758"]],
    @"ご飯+とり肉" : @[[[TRFood alloc] initWithName:@"チキンライス" andId:@"14-122-552"], [[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"], [[TRFood alloc] initWithName:@"鶏丼" andId:@"14-130-545"]],
    @"ご飯+にんじん" : @[[[TRFood alloc] initWithName:@"クッパ" andId:@"14-133-758"]],
    @"ご飯+にんにく" : @[[[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"]],
    @"ご飯+ぶた肉" : @[[[TRFood alloc] initWithName:@"豚丼" andId:@"14-130-544"]],
    @"ご飯+トマト" : @[[[TRFood alloc] initWithName:@"タコライス" andId:@"14-124-568"]],
    @"ご飯+牛乳" : @[[[TRFood alloc] initWithName:@"リゾット" andId:@"14-133-351"], [[TRFood alloc] initWithName:@"ドリア" andId:@"14-135-143"]],
    @"ご飯+玉ねぎ" : @[[[TRFood alloc] initWithName:@"オムライス" andId:@"14-121-553"], [[TRFood alloc] initWithName:@"チキンライス" andId:@"14-122-552"], [[TRFood alloc] initWithName:@"タコライス" andId:@"14-124-568"], [[TRFood alloc] initWithName:@"ロコモコ" andId:@"14-125-569"], [[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"], [[TRFood alloc] initWithName:@"ピラフ" andId:@"14-127-142"], [[TRFood alloc] initWithName:@"あんかけチャーハン" andId:@"14-131-892"]],
    @"たまご+にんじん" : @[[[TRFood alloc] initWithName:@"ビビンバ" andId:@"14-132-352"], [[TRFood alloc] initWithName:@"クッパ" andId:@"14-133-758"]],
    @"たまご+にんにく" : @[[[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"], [[TRFood alloc] initWithName:@"パッタイ" andId:@"25-249-744"]],
    @"たまご+ぶた肉" : @[[[TRFood alloc] initWithName:@"お好み焼き" andId:@"16-158-176"], [[TRFood alloc] initWithName:@"スンドゥブチゲ" andId:@"25-247-750"]],
    @"たまご+ベーコン" : @[[[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"]],
    @"たまご+牛乳" : @[[[TRFood alloc] initWithName:@"キッシュ" andId:@"13-119-307"], [[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"], [[TRFood alloc] initWithName:@"タルト" andId:@"21-207-193"], [[TRFood alloc] initWithName:@"プリン・プディング" andId:@"21-211-197"], [[TRFood alloc] initWithName:@"エクレア" andId:@"21-212-992"], [[TRFood alloc] initWithName:@"ホットケーキ・パンケーキ" andId:@"21-215-192"], [[TRFood alloc] initWithName:@"ドーナッツ・ドーナツ" andId:@"21-216-196"], [[TRFood alloc] initWithName:@"クリームパン" andId:@"22-221-207"], [[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"], [[TRFood alloc] initWithName:@"フレンチトースト" andId:@"22-228-580"], [[TRFood alloc] initWithName:@"チュロス" andId:@"25-256-734"]],
    @"たまご+玉ねぎ" : @[[[TRFood alloc] initWithName:@"ポテトコロッケ" andId:@"13-118-867"], [[TRFood alloc] initWithName:@"かぼちゃコロッケ" andId:@"13-118-869"], [[TRFood alloc] initWithName:@"さつまいもコロッケ" andId:@"13-118-873"], [[TRFood alloc] initWithName:@"オムレツ" andId:@"13-119-644"], [[TRFood alloc] initWithName:@"オムライス" andId:@"14-121-553"], [[TRFood alloc] initWithName:@"ロコモコ" andId:@"14-125-569"], [[TRFood alloc] initWithName:@"親子丼" andId:@"14-130-541"], [[TRFood alloc] initWithName:@"あんかけチャーハン" andId:@"14-131-892"], [[TRFood alloc] initWithName:@"ナシゴレン" andId:@"14-131-894"], [[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"], [[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"], [[TRFood alloc] initWithName:@"トルティージャ・トルティーヤ" andId:@"25-256-733"], [[TRFood alloc] initWithName:@"ハンバーグ" andId:@"10-278-641"], [[TRFood alloc] initWithName:@"ロールキャベツ" andId:@"10-278-646"]],
    @"とり肉+にんじん" : @[[[TRFood alloc] initWithName:@"筑前煮・がめ煮【福岡】" andId:@"25-245-679"]],
    @"とり肉+にんにく" : @[[[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"]],
    @"とり肉+牛乳" : @[[[TRFood alloc] initWithName:@"チキングラタン" andId:@"15-149-907"]],
    @"とり肉+玉ねぎ" : @[[[TRFood alloc] initWithName:@"チキンライス" andId:@"14-122-552"], [[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"], [[TRFood alloc] initWithName:@"チキングラタン" andId:@"15-149-907"], [[TRFood alloc] initWithName:@"タッカルビ" andId:@"25-247-754"], [[TRFood alloc] initWithName:@"ゲーン（タイカレー）" andId:@"25-249-743"]],
    @"にんじん+にんにく" : @[[[TRFood alloc] initWithName:@"ドライカレー" andId:@"14-120-551"], [[TRFood alloc] initWithName:@"スープカレー" andId:@"14-120-566"], [[TRFood alloc] initWithName:@"ミートソースパスタ" andId:@"15-137-590"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"]],
    @"にんじん+ぶた肉" : @[[[TRFood alloc] initWithName:@"ポークカレー" andId:@"14-120-884"], [[TRFood alloc] initWithName:@"豚汁" andId:@"17-161-790"], [[TRFood alloc] initWithName:@"カレー鍋" andId:@"23-234-538"]],
    @"にんじん+トマト" : @[[[TRFood alloc] initWithName:@"ミネストローネ" andId:@"25-250-726"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"]],
    @"にんじん+ベーコン" : @[[[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"]],
    @"にんじん+牛乳" : @[[[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"]],
    @"にんじん+玉ねぎ" : @[[[TRFood alloc] initWithName:@"ポークカレー" andId:@"14-120-884"], [[TRFood alloc] initWithName:@"野菜カレー" andId:@"14-120-564"], [[TRFood alloc] initWithName:@"ビーフカレー" andId:@"14-120-885"], [[TRFood alloc] initWithName:@"キーマカレー" andId:@"14-120-563"], [[TRFood alloc] initWithName:@"ドライカレー" andId:@"14-120-551"], [[TRFood alloc] initWithName:@"スープカレー" andId:@"14-120-566"], [[TRFood alloc] initWithName:@"ミートソースパスタ" andId:@"15-137-590"], [[TRFood alloc] initWithName:@"クリームシチュー" andId:@"17-163-924"], [[TRFood alloc] initWithName:@"コンソメスープ" andId:@"17-167-86"], [[TRFood alloc] initWithName:@"トマトスープ" andId:@"17-168-87"], [[TRFood alloc] initWithName:@"ポトフ" andId:@"17-173-483"], [[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"], [[TRFood alloc] initWithName:@"にんじんスープ" andId:@"17-173-345"], [[TRFood alloc] initWithName:@"豆スープ" andId:@"17-173-343"], [[TRFood alloc] initWithName:@"タジン鍋" andId:@"23-234-628"], [[TRFood alloc] initWithName:@"チャプチェ" andId:@"25-247-756"], [[TRFood alloc] initWithName:@"ボルシチ" andId:@"25-248-1060"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"], [[TRFood alloc] initWithName:@"肉じゃが" andId:@"10-275-631"], [[TRFood alloc] initWithName:@"酢豚" andId:@"10-276-699"]],
    @"にんにく+ぶた肉" : @[[[TRFood alloc] initWithName:@"サムギョプサル" andId:@"25-247-753"]],
    @"にんにく+トマト" : @[[[TRFood alloc] initWithName:@"トマトソース" andId:@"19-192-239"], [[TRFood alloc] initWithName:@"ビリヤニ" andId:@"25-251-770"], [[TRFood alloc] initWithName:@"ラタトゥイユ・ラタツーユ" andId:@"25-252-709"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"]],
    @"にんにく+ベーコン" : @[[[TRFood alloc] initWithName:@"ペペロンチーノ" andId:@"15-139-355"], [[TRFood alloc] initWithName:@"きのこパスタ" andId:@"15-142-904"]],
    @"にんにく+牛乳" : @[[[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"]],
    @"にんにく+玉ねぎ" : @[[[TRFood alloc] initWithName:@"ドライカレー" andId:@"14-120-551"], [[TRFood alloc] initWithName:@"スープカレー" andId:@"14-120-566"], [[TRFood alloc] initWithName:@"パエリア" andId:@"14-126-303"], [[TRFood alloc] initWithName:@"ミートソースパスタ" andId:@"15-137-590"], [[TRFood alloc] initWithName:@"トマトクリーム" andId:@"15-137-897"], [[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"], [[TRFood alloc] initWithName:@"トマトソース" andId:@"19-192-239"], [[TRFood alloc] initWithName:@"トマト鍋" andId:@"23-234-537"], [[TRFood alloc] initWithName:@"ビリヤニ" andId:@"25-251-770"], [[TRFood alloc] initWithName:@"ラタトゥイユ・ラタツーユ" andId:@"25-252-709"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"]],
    @"ぶた肉+玉ねぎ" : @[[[TRFood alloc] initWithName:@"ポークカレー" andId:@"14-120-884"]],
    @"トマト+玉ねぎ" : @[[[TRFood alloc] initWithName:@"インド風カレー" andId:@"14-120-886"], [[TRFood alloc] initWithName:@"タコライス" andId:@"14-124-568"], [[TRFood alloc] initWithName:@"パスタソース" andId:@"15-144-242"], [[TRFood alloc] initWithName:@"トマトソース" andId:@"19-192-239"], [[TRFood alloc] initWithName:@"ビリヤニ" andId:@"25-251-770"], [[TRFood alloc] initWithName:@"ラタトゥイユ・ラタツーユ" andId:@"25-252-709"], [[TRFood alloc] initWithName:@"ブイヤベース" andId:@"25-252-712"], [[TRFood alloc] initWithName:@"ワカモレ" andId:@"25-253-779"], [[TRFood alloc] initWithName:@"サルサ" andId:@"25-253-786"]],
    @"ベーコン+牛乳" : @[[[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"], [[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"]],
    @"ベーコン+玉ねぎ" : @[[[TRFood alloc] initWithName:@"ナポリタン" andId:@"15-137-589"], [[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"], [[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"]],
    @"牛乳+玉ねぎ" : @[[[TRFood alloc] initWithName:@"カルボナーラ" andId:@"15-138-356"], [[TRFood alloc] initWithName:@"かぼちゃのグラタン" andId:@"15-149-906"], [[TRFood alloc] initWithName:@"シーフードグラタン" andId:@"15-149-808"], [[TRFood alloc] initWithName:@"チキングラタン" andId:@"15-149-907"], [[TRFood alloc] initWithName:@"かぼちゃスープ" andId:@"17-173-342"], [[TRFood alloc] initWithName:@"チャウダー" andId:@"17-173-482"], [[TRFood alloc] initWithName:@"ケークサレ（塩ケーキ）" andId:@"22-228-621"]]
    };
    //----AutoGenerated
    
}

-(NSArray *)recipesFor:(NSString*)ingredient1 and:(NSString*)ingredient2
{
    if (!recipesDictionary) {
        [self initDictonary];
    }
    
    if ([ingredient1 compare:ingredient2] == NSOrderedDescending) {
        // swap
        NSString *tmp = ingredient1;
        ingredient1 = ingredient2;
        ingredient2 = tmp;
    }
    NSString *key = [ingredient1 stringByAppendingString:[@"+" stringByAppendingString:ingredient2]];
    
    return [recipesDictionary objectForKey:key];
}
@end
